version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    stdin_open: true
    ports:
      - "7000:7000"
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/ToDoData
  mongo-db:
    image: mongo
    container_name: mongo
    volumes:
      - ./data/dev:/data/db
    ports:
      - "27017:27017"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    stdin_open: true
    command: npm start
    depends_on:
      - server
    ports:
      - "3000:3000"
volumes:
  mongodata:
